# http://module-build.sourceforge.net/META-spec.html
#XXXXXXX This is a prototype!!!  It will change in the future!!! XXXXX#
name:         DateTime-Fiction-JRRTolkien-Shire
version:      0.01
version_from: lib/DateTime/Fiction/JRRTolkien/Shire.pm
installdirs:  site
requires:
    DateTime:                      0.14

distribution_type: module
generated_by: ExtUtils::MakeMaker version 6.17
